#!/usr/bin/env bash
# -*- coding: utf-8 -*-

../src/configure --enable-csdefault --enable-libs --enable-standalone --prefix=/usr/local/racket


# >>> Installation targets:
#  executables        : ${exec_prefix}/bin/...
#  core docs          : ${datarootdir}/doc/${PACKAGE}/...
#  C libraries        : ${exec_prefix}/lib/...
#  C headers          : ${prefix}/include/${PACKAGE}/...
#  platform libraries : ${exec_prefix}/lib/${PACKAGE}/...
#  common libraries   : ${datarootdir}/${PACKAGE}/...
#  base collections   : ${exec_prefix}/share/${PACKAGE}/collects/...
#  configuration      : ${prefix}/etc/${PACKAGE}/...
#  .desktop files     : ${exec_prefix}/share/applications/...
#  man pages          : ${datarootdir}/man/...
#      where prefix = /usr/local/racket
#   and datarootdir = ${prefix}/share
#   and exec_prefix = ${prefix}
#   and PACKAGE = racket
