# shellcheck source=/dev/null # https://www.shellcheck.net/wiki/SC1091
source "$HOME/.bashrc"

# if removing graphic login, this needs to be enabled
# Intercept TTY1 to launch the Wayland compositor
# if [ "$(tty)" = "/dev/tty1" ]; then
#     export XDG_SESSION_TYPE=wayland
#     export XDG_CURRENT_DESKTOP=sway
#     exec dbus-run-session sway
# fi

# show if there is an existing tmux session when SSH into this machine
[[ -n $SSH_CLIENT ]] && tmux ls # && tmux attach
