# vim: set fdl=99:
source "$HOME/.bashrc"

_complete_ssh_hosts ()
{
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        comp_ssh_hosts=$(cut -f 1 -d ' ' ~/.ssh/known_hosts | \
                        sed -e s/,.*//g | \
                        grep -v ^# | \
                        uniq | \
                        grep -v "\[" ;
                        grep "^Host " ~/.ssh/config | \
                        awk '{print $2}'
                )
        COMPREPLY=( $(compgen -W "${comp_ssh_hosts}" -- $cur))
        return 0
}
complete -F _complete_ssh_hosts ssh

. "$HOME/.local/bin/env"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if __conda_setup="$('/opt/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"; then
    eval "$__conda_setup"
else
    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<



# Added by Windsurf
export PATH="$HOME/.codeium/windsurf/bin:$PATH"

# added by Snowflake SnowflakeCLI installer v1.0
export PATH=/Applications/SnowflakeCLI.app/Contents/MacOS/:$PATH

# add specific bash only environment
export PATH="/opt/bash/bin:$PATH"

# gh cli completion
# eval "$($HOME/Code/gitapi/git_env/bin/gh completion -s bash)"

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# >>> nvwb
# Sourcing the nvwb wrapper function was added during the NVIDIA AI Workbench installation and
# is required for NVIDIA AI Workbench to function properly. When uninstalling
# NVIDIA AI Workbench, it will be removed.
source $HOME/.local/share/nvwb/nvwb-wrapper.sh
# >>> nvwb

eval "$(/opt/homebrew/bin/brew shellenv)"

# Added by Antigravity
export PATH="/Users/ahadjigeorgalis/.antigravity/antigravity/bin:$PATH"
