---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
    force_apt_get: yes

- name: Verify git ppa is an apt repository
  become: true
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: no

- name: Install system software
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400 #One day
    autoremove: yes
    force_apt_get: yes
  vars:
    packages:
    - git-core
    - curl
    - tmux

- name: Clone dotfiles git repo
  git:
    repo: git@github.com:AntoniosHadji/dotfiles.git
    dest: /home/antonios/.dotfiles
    accept_hostkey: yes
    recursive: yes

- name: Create symlinks
  file:
    src: '/home/antonios/.dotfiles/{{ item }}'
    dest: '/home/antonios/.{{ item }}'
    state: link
  with_items:
    - 'vim'
    - 'tmux.conf'
