---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
    force_apt_get: yes

- name: Verify git ppa is an apt repository
  become: true
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: no

- name: Install system software
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400 #One day
    autoremove: yes
    force_apt_get: yes
  vars:
    packages:
    - git-core
    - curl
    - tmux
    - tree
    - silversearcher-ag

- name: Clone dotfiles git repo
  git:
    repo: git@github.com:AntoniosHadji/dotfiles.git
    dest: "$HOME/.dotfiles"
    accept_hostkey: yes
    recursive: yes

- name: Create symlinks
  file:
    src: "$HOME/.dotfiles/{{ item }}"
    dest: "$HOME/.{{ item }}"
    state: link
  with_items:
    - 'bashrc'
    - 'curlrc'
    - 'dircolors'
    - 'eslintrc.json'
    - 'gitconfig'
    - 'inputrc'
    - 'pam_environment'
    - 'tern-project'
    - 'tmux.conf'
    - 'vim'

# install vim plugins with vim-plug
# if command -v vim; then
#   vim +PluginInstall +qall
# fi
# Python3: only install extra software in python 3
# TODO: verify if -HE is correct when using pip with --user
# if ! command -v pip3; then
#   curl -sL https://bootstrap.pypa.io/get-pip.py | sudo -HE python3 -
# else
#   pip3 install --user --upgrade -r ~/dotfiles/requirements3.txt
# fi
