---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: verify git repo is available
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: no

- name: install system software
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400 #One day
    autoremove: yes
    force_apt_get: yes
  vars:
    packages:
    - git-core

