---
all:
  children:
    desktop:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
    server:
      hosts:
        nxtest-wc-01p.sys.comcast.net:
