---
- hosts: localhost
  tasks:
    - debug:
        msg: "Gateway {{ ansible_default_ipv4.gateway }}"
      when: ansible_default_ipv4.gateway is defined

    # Example that prints return information from the previous task
    - shell: /usr/bin/uptime
      register: result

    - debug:
        var: result
        verbosity: 2
        # only shows when verbosity is set to this level or higher

    - name: Operating System
      debug:
        msg:
          - "{{ ansible_distribution }}"
          - "{{ ansible_distribution_file_variety }}"
          - "{{ ansible_distribution_major_version }}"

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 4
        # only shows when verbosity is set to this level or higher
        # shows correct var names for use in ansible scripts
