---
- hosts: all
  roles:
    - common
    - docker

# primary home workstation and laptop only
- hosts: desktop
  roles:
    - desktop
    - python_tools
    - dropbox

# primary workstation only
- hosts: workstation
  roles:
    - primary
