---
- name: Ubuntu Packaging Guide software install
  # http://packaging.ubuntu.com/singlehtml/index.html#document-ubuntu-packaging-guide/getting-set-up
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    force_apt_get: yes
  vars:
    packages:
      - gnupg
      - pbuilder
      - ubuntu-dev-tools
      - apt-file

- name: Build dependencies for Gnucash
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    force_apt_get: yes
  vars:
    packages:
      - cmake
      - libglib2.0-dev
      - libgtk-3-dev
      - guile-2.2-dev
      - libxml2-dev
      - libxml2-utils
      - xsltproc
      - libxslt1-dev
      - libicu-dev
      - libboost1.65-all-dev
      - libwebkit2gtk-4.0-dev
      - swig
      - libaqbanking-dev
      - libgwenhywfar60-dev
      - libktoblzcheck1-dev
      - libdbi-dev
      - libdbd-mysql
      - libdbd-pgsql
      - libdbd-sqlite3
      - libofx-dev
      - python3-dev
      - libsecret-1-dev
      - libfinance-quote-perl

- name: Java Software development
  become: true
  apt:
    name: openjdk-11-jdk
    state: latest
    force_apt_get: yes

- name: Python tools
  become: true
  apt:
    name: python3-venv
    state: latest
    force_apt_get: yes

- name: Python3.7 build dependencies
  become: true
  apt:
    name: Python3.7
    state: build-dep
    force_apt_get: yes

