---
- name: Update and upgrade apt packages
  when: ansible_distribution_file_variety == "Debian"
  become: true
  apt:
    upgrade: "dist"
    update_cache: true
    autoremove: true
    force_apt_get: true

- name: Install system software
  when: ansible_distribution_file_variety == "Debian"
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    force_apt_get: true
  loop:
    - git
    - vim
    - pandoc
    - curl
    - tmux
    - tree
    - rename
    - openssh-server
    - shellcheck
    - fonts-powerline
    - net-tools
    - jq
