---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true
    autoremove: true
    force_apt_get: true

- name: Install system software
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    force_apt_get: true
  vars:
    packages:
      - git
      - curl
      - tmux
      - tree
      - rename
      - vim
      - openssh-server
      - pandoc
      - shellcheck
      - fonts-powerline
      - net-tools
      - silversearcher-ag

- name: Clone dotfiles git repo
  git:
    repo: git@github.com:AntoniosHadji/dotfiles.git
    dest: "$HOME/.config/dotfiles"
    accept_hostkey: true
    recursive: true
  tags:
    - update

- name: Create symlinks
  file:
    src: "$HOME/.config/dotfiles/{{ item }}"
    path: "$HOME/.{{ item }}"
    state: link
    force: true
  with_items:
    - 'bashrc'
    - 'curlrc'
    - 'dircolors'
    - 'eslintrc.json'
    - 'gitconfig'
    - 'inputrc'
    - 'pam_environment'
    - 'tern-project'
    - 'tmux.conf'
    - 'vim'
  tags:
    - update

# install rust
# install ripgrep
