---
- name: Clone dotfiles git repo
  git:
    repo: git@github.com:AntoniosHadji/dotfiles.git
    dest: "$HOME/.config/dotfiles"
    accept_hostkey: true
    recursive: true

- name: Create symlinks
  file:
    src: "$HOME/.config/dotfiles/{{ item }}"
    path: "$HOME/.{{ item }}"
    state: link
    force: true
  loop:
    - "bashrc"
    - "curlrc"
    - "eslintrc.json"
    - "gitconfig"
    - "inputrc"
    - "pam_environment"
    - "tern-project"
    - "tmux.conf"
    - "vim"
    # - 'dircolors'
    #    not needed no current ubuntu setup
