---
- name: Update and upgrade apt packages
  when: ansible_distribution_file_variety == "Debian"
  become: true
  apt:
    upgrade: dist
    update_cache: true
    autoremove: true
    force_apt_get: true

- name: Install system software
  when: ansible_distribution_file_variety == "Debian"
  become: true
  apt:
    name:
      - apt-transport-https
      - curl
      - fonts-powerline
      - git
      - jq
      - net-tools
      - openssh-server
      - pandoc
      - rename
      - shellcheck
      - tmux
      - tree
      - vim
    state: latest
    force_apt_get: true
