---
- name: Install frequently used software
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    force_apt_get: true
  vars:
    packages:
      - calibre

- name: install teamviewer from URL
  become: true
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
