---
- name: Java Software development
  become: true
  tags: java
  apt:
    name: openjdk-8-jdk
    state: latest
    force_apt_get: true

- name: C language tools
  become: true
  apt:
    name:
      - exuberant-ctags
      - google-perftools
      - libgoogle-perftools-dev
      - valgrind
      - kcachegrind
      - tau
