---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    autoremove: yes
    force_apt_get: yes

- name: Verify git ppa is an apt repository
  become: true
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
    update_cache: yes

- name: Add/Verify vim ppa for latest vim8
  become: true
  apt_repository:
    repo: ppa:jonathonf/vim
    state: present
    update_cache: yes

- name: Install system software
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    force_apt_get: yes
  vars:
    packages:
    - git
    - curl
    - tmux
    - tree
    - rename
    - vim
    - openssh-server
    - pandoc
    - shellcheck
    - fonts-powerline
    - net-tools
    - silversearcher-ag

- name: Clone dotfiles git repo
  git:
    repo: git@github.com:AntoniosHadji/dotfiles.git
    dest: "$HOME/.dotfiles"
    accept_hostkey: yes
    recursive: yes
    # track_submodules: yes # this causes submodules of submodules to update

- name: Create symlinks
  file:
    src: "$HOME/.dotfiles/{{ item }}"
    path: "$HOME/.{{ item }}"
    state: link
    force: yes
  with_items:
    - 'bashrc'
    - 'curlrc'
    - 'dircolors'
    - 'eslintrc.json'
    - 'gitconfig'
    - 'inputrc'
    - 'pam_environment'
    - 'tern-project'
    - 'tmux.conf'
    - 'vim'

# install rust
# install ripgrep
