---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: "dist"
    update_cache: true
    autoremove: true
    force_apt_get: true

- name: Install system software
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    force_apt_get: true
  loop:
    - git
    - curl
    - tmux
    - tree
    - rename
    - vim
    - openssh-server
    - pandoc
    - shellcheck
    - fonts-powerline
    - net-tools
    - jq

- name: Clone dotfiles git repo
  git:
    repo: git@github.com:AntoniosHadji/dotfiles.git
    dest: "$HOME/.config/dotfiles"
    accept_hostkey: true
    recursive: true
  tags: dotfiles

- name: Create symlinks
  file:
    src: "$HOME/.config/dotfiles/{{ item }}"
    path: "$HOME/.{{ item }}"
    state: link
    force: true
  loop:
    - "bashrc"
    - "curlrc"
    - "eslintrc.json"
    - "gitconfig"
    - "inputrc"
    - "pam_environment"
    - "tern-project"
    - "tmux.conf"
    - "vim"
    # - 'dircolors'
    #    not needed no current ubuntu setup
  tags: dotfiles

- name: Tools for use with tiling wm
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    force_apt_get: true
  loop:
    - "maim"
    # import tool is related to inkscape? might be better
# install rust
# install ripgrep
# install fd
# install alacritty
# build vim
