---
- name: Add Apt signing key for google software
  become: true
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: install google chrome
  become: true
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    state: present

- name: Install desktop software
  become: true
  apt:
    name:
     - chrome-gnome-shell
     - gnome-tweaks
     - dot2tex
     - texlive
     - texlive-latex-extra
     - texlive-latex-extra-doc
     - texlive-pictures
     - texlive-pictures-doc
     - texlive-science
     - texlive-science-doc
    state: latest
    force_apt_get: yes
