---
- name: Create Directory Structures if they do not exist
  file:
    path: "$HOME/{{ item }}"
    state: directory
  loop:
    # creates whole structure inside path above
    - ".config/powerline/themes/vim"

- name: Clone dotfiles git repo
  git:
    repo: git@github.com:AntoniosHadji/dotfiles.git
    dest: "$HOME/.config/dotfiles"
    accept_hostkey: true
    recursive: true

- name: Create symlinks
  file:
    src: "$HOME/.config/dotfiles/{{ item }}"
    path: "$HOME/.{{ item }}"
    state: link
    force: true
  loop:
    - "bashrc"
    - "curlrc"
    - "eslintrc.json"
    - "gitconfig"
    - "inputrc"
    - "pam_environment"
    - "tern-project"
    - "tmux.conf"
    - "vim"
    - "xinitrc"
    - "fzf"
    # - 'dircolors'
    #    not needed no current ubuntu setup

- name: Create Powerline Config Symlink
  file:
    src: "$HOME/.config/dotfiles/powerline/config.json"
    path: "$HOME/.config/powerline/config.json"
    state: link
    force: true

- name: Create Powerline Theme Symlink
  file:
    src: "$HOME/.config/dotfiles/powerline/themes/vim/default.json"
    path: "$HOME/.config/powerline/themes/vim/default.json"
    state: link
    force: true
